#!/system/bin/sh

echo 0 > /proc/sys/vm/swappiness
echo 0 > /proc/sys/vm/dirty_expire_centisecs
echo 0 > /proc/sys/vm/dirty_writeback_centisecs
echo 60 > /proc/sys/vm/dirty_background_ratio
echo 95 > /proc/sys/vm/dirty_ratio
echo 10 > /proc/sys/vm/vfs_cache_pressure
echo 4096 > /proc/sys/vm/min_free_kbytes

### Uncomment this for more battery life, bul slightly less perfomance
#echo "100000" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/sampling_rate
#echo "300" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/powersave_bias
#echo "75" > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/up_threshold

echo "nameserver 0.0.0.0" > /etc/resolv.conf